### ISSUE TITLE
Hotkeys activate when typing a comment.

### ISSUE THREAD

**Issue by ajloveslily14** [CalumJEadie/frame-by-frame#15]
If you write a comment with the letter p in it is changes the video speed.

**Comment by Epono** [comment]
I'll add, whatever the focus is, the letter p causes the change of the video speed

**Comment by Templarfreak** [comment]
This is a consistent issue and should be fixed. At the least, a menu to turn this hotkey on or off would be fine. All the other hotkeys do don't really have consistent problems with, except this one.

**Comment by CalumJEadie** [comment]
Thanks for this feedback. For the moment I've disabled the keyboard functionality with #16. I'll look out for the feedback on the removed functionality and if it's missed will work out a plan to support it without the hotkey activation issue when typing in search and comments.
