### ISSUE TITLE
Support for new YouTube player and 60 FPS

### ISSUE THREAD

**Issue by Long-Horse** [CalumJEadie/frame-by-frame#6]
http://youtube.com/testtube introduces a preview at the new YouTube player and FrameScroll doesn't show it's buttons on that player. Can this be implemented?

Also, does it work properly with 60 FPS videos? Or does it act as if it's 30 FPS? 

Also, most of the time, it doesn't appear until I refresh the page. This is fairly recent.

**Comment by CalumJEadie** [comment]
Hey @Long-Horse, thanks for bring this up!

> http://youtube.com/testtube introduces a preview at the new YouTube player and FrameScroll doesn't show it's buttons on that player. Can this be implemented?

Will require a couple of tweaks to the logic around injecting the player however not a huge change.

> Also, does it work properly with 60 FPS videos? Or does it act as if it's 30 FPS?

At the moment I believe it'll be acting as 30 FPS. That can also be addressed.

> Also, most of the time, it doesn't appear until I refresh the page. This is fairly recent.

Ok. Would be great to pin down the exact situations that causes this.


Would you be interested in working on the above? By all means get involved! I'm very happy to walk you through the code base and to put some suggestions forward how to approach the above.

**Comment by Long-Horse** [comment]
I have no experience in coding :/ Unless it's magically written in HTML. I doubt I can be any help.

**Comment by CalumJEadie** [comment]
Cheers for the heads up on this @Long-Horse! I've just released a version that brings the extension up to date with YouTube.
