### ISSUE TITLE
YouTube HTML5 player launched. Plugin does not work.

### ISSUE THREAD

**Issue by dan96kid** [CalumJEadie/frame-by-frame#7]
Earlier this month YouTube updated the video player. Now the plugin doesn't work. The buttons for going frame-by-frame don't appear.
![fbfmb](https://cloud.githubusercontent.com/assets/14021093/9555870/f239be14-4d95-11e5-8f93-ded2b770640b.png)

**Comment by badger200** [comment]
Same here on Windows XP / Chromium 46. @CalumJEadie Any thoughts?

**Comment by CalumJEadie** [comment]
Cheers for the heads up on this @dan96kid and @badger200! I've just released a version that brings the extension up to date with YouTube.

**Comment by badger200** [comment]
Thanks so much @CalumJEadie for fixing this! I don't know why but for some reason the notification email didn't show up in my Gmail until today, despite being dated Nov 12th. I'll update and report back if I encounter any issues. I really appreciate you following up! :+1:
