### ISSUE TITLE
Sometimes buttons do not load

### ISSUE THREAD

**Issue by CalumJEadie** [CalumJEadie/frame-by-frame#8]
Workaround:
- Reload page

Cause:
- YouTube not fully loaded when Frame by Frame loads?

Fix:
- Give YouTube a grace period to load

**Comment by regularWand** [comment]
I think I've figured out why buttons do not load sometimes. It seems to occur only when following a session link from any Youtube page besides a video page (e.g. the home page or search results page). When these pages are loaded, content-script.js is not loaded as these urls are not defined as matches in manifest.json. Additionally, if frame-by-frame.js is loaded on these pages, it cannot grab the HTML elements it needs to function. I've committed a potential fix for this at 35c5105.

**Comment by CalumJEadie** [comment]
Great work!

I'm very happy to either take a PR request with these changes isolated or to release them as part of a larger release.
